
config:
#  threshould-temp: 100.0
#  threshould-warning: 30000
#  threshould-normal: 30000
#  threshould-watermark: "30 seconds"
#  duration-window: "30 seconds"
#  duration-slide: "6 seconds"
sw:
#  output-mode: "append"
#  output-mode: "update"

sub:
  kafka:
    tenant-name: "YOUR TENANT NAME"
    pool-id: "YOUR STREAMING POOL ID"
    streaming-server: "YOUR STREAMING SERVER URL"
    user-name: "YOUR USER NAME"
    auth-token: "YOUR AUTH TOKEN"
    topic: "TOPIC TO SUBSCRIBE"
  
pub:
  kafka:
    tenant-name: "YOUR TENANT NAME"
    pool-id: "YOUR STREAMING POOL ID"
    streaming-server: "YOUR STREAMING SERVER URL"
    user-name: "YOUR USER NAME"
    auth-token: "YOUR AUTH TOKEN"
    topic: "TOPIC TO PUBLISH"
    checkpoint-location: "/var/tmp/tempmon/checkpoint"


