kafka:
  tenant-name: "YOUR TENANT NAME"
  pool-id: "YOUR STREAMING POOL ID"
  streaming-server: "YOUR STREAMING SERVER URL"
  user-name: "YOUR USER NAME"
  auth-token: "YOUR AUTH TOKEN"

temp-reporter:
  enabled: true
  polling-interval: 5000
  kafka:
    tenant-name: "${ALIAS=kafka.tenant-name}"
    pool-id: "${ALIAS=kafka.pool-id}"
    streaming-server: "${ALIAS=kafka.streaming-server}"
    user-name: "${ALIAS=kafka.user-name}"
    auth-token: "${ALIAS=kafka.auth-token}"
    topic: "TOPIC TO PUBLISH"

slack-alerter:
  enabled: true
  webhook-url: "SLACK WEBHOOK URL"
  kafka:
    tenant-name: "${ALIAS=kafka.tenant-name}"
    pool-id: "${ALIAS=kafka.pool-id}"
    streaming-server: "${ALIAS=kafka.streaming-server}"
    user-name: "${ALIAS=kafka.user-name}"
    auth-token: "${ALIAS=kafka.auth-token}"
    topic: "TOPIC TO SUBSCRIBE"
    group-id: "GROUP_01"
